### ISSUE TITLE
Tracking issue for peer IDs as CIDs

### ISSUE THREAD

**Issue by Stebalien** [libp2p/specs#216]
RFC: https://github.com/libp2p/specs/pull/209

This RFC outlines the process for moving from formatting peer IDs as base58 multihashes to formatting them as CIDs with a special libp2p-key multicodec (0x72).

This RFC _does not_ change the in-memory and/or network representation of peer IDs, just the textual format.

This process has two stages that must be completed in order:
* [ ] Stage 1: Parse CIDs as peer IDs.
* [ ] Stage 2: Format peer IDs as CIDs by default.

Tracking status of all libp2p implementations:
* go-libp2p
  * [ ] Support the libp2p-key multicodec.
  * [ ] Support parsing CIDs as peer IDs.
    - PRs:
      - [ ] https://github.com/libp2p/go-libp2p-core/pull/41
  * [ ] Output peer IDs as CIDs by default
* js-libp2p
  * [ ] Support the libp2p-key multicodec.
  * [ ] Support parsing CIDs as peer IDs.
  * [ ] Output peer IDs as CIDs by default
* rust-libp2p
  * [ ] Support the libp2p-key multicodec.
  * [ ] Support parsing CIDs as peer IDs.
  * [ ] Output peer IDs as CIDs by default
* java-libp2p
  * [ ] Support the libp2p-key multicodec.
  * [ ] Support parsing CIDs as peer IDs.
  * [ ] Output peer IDs as CIDs by default
* python-libp2p
  * [ ] Support the libp2p-key multicodec.
  * [ ] Support parsing CIDs as peer IDs.
  * [ ] Output peer IDs as CIDs by default

**Comment by Arlodotexe** [comment]
Tracking issue for the .NET side https://github.com/ipfs-shipyard/net-ipfs-core/issues/26
